const express = require("express");
const router = express.Router();
const controller_dashboard = require("../controllers/admin/dashboardController");
router.get("/dashboard", controller_dashboard.index.bind(controller_dashboard));
router.get("/dashboard/:id", controller_dashboard.show.bind(controller_dashboard));
const controller_user = require("../controllers/admin/userController");
router.get("/user", controller_user.index.bind(controller_user));
router.get("/user/:id", controller_user.show.bind(controller_user));
const controller_student = require("../controllers/admin/studentController");
router.get("/student", controller_student.index.bind(controller_student));
router.get("/student/:id", controller_student.show.bind(controller_student));
const controller_expert = require("../controllers/admin/expertController");
router.get("/expert", controller_expert.index.bind(controller_expert));
router.get("/expert/:id", controller_expert.show.bind(controller_expert));
const controller_corporate = require("../controllers/admin/corporateController");
router.get("/corporate", controller_corporate.index.bind(controller_corporate));
router.get("/corporate/:id", controller_corporate.show.bind(controller_corporate));
const controller_course = require("../controllers/admin/courseController");
router.get("/course", controller_course.index.bind(controller_course));
router.get("/course/:id", controller_course.show.bind(controller_course));
const controller_module = require("../controllers/admin/moduleController");
router.get("/module", controller_module.index.bind(controller_module));
router.get("/module/:id", controller_module.show.bind(controller_module));
const controller_lesson = require("../controllers/admin/lessonController");
router.get("/lesson", controller_lesson.index.bind(controller_lesson));
router.get("/lesson/:id", controller_lesson.show.bind(controller_lesson));
const controller_assignment = require("../controllers/admin/assignmentController");
router.get("/assignment", controller_assignment.index.bind(controller_assignment));
router.get("/assignment/:id", controller_assignment.show.bind(controller_assignment));
const controller_quiz = require("../controllers/admin/quizController");
router.get("/quiz", controller_quiz.index.bind(controller_quiz));
router.get("/quiz/:id", controller_quiz.show.bind(controller_quiz));
const controller_certificate = require("../controllers/admin/certificateController");
router.get("/certificate", controller_certificate.index.bind(controller_certificate));
router.get("/certificate/:id", controller_certificate.show.bind(controller_certificate));
const controller_badge = require("../controllers/admin/badgeController");
router.get("/badge", controller_badge.index.bind(controller_badge));
router.get("/badge/:id", controller_badge.show.bind(controller_badge));
const controller_appointment = require("../controllers/admin/appointmentController");
router.get("/appointment", controller_appointment.index.bind(controller_appointment));
router.get("/appointment/:id", controller_appointment.show.bind(controller_appointment));
const controller_event = require("../controllers/admin/eventController");
router.get("/event", controller_event.index.bind(controller_event));
router.get("/event/:id", controller_event.show.bind(controller_event));
const controller_webinar = require("../controllers/admin/webinarController");
router.get("/webinar", controller_webinar.index.bind(controller_webinar));
router.get("/webinar/:id", controller_webinar.show.bind(controller_webinar));
const controller_blog = require("../controllers/admin/blogController");
router.get("/blog", controller_blog.index.bind(controller_blog));
router.get("/blog/:id", controller_blog.show.bind(controller_blog));
const controller_resource = require("../controllers/admin/resourceController");
router.get("/resource", controller_resource.index.bind(controller_resource));
router.get("/resource/:id", controller_resource.show.bind(controller_resource));
const controller_payment = require("../controllers/admin/paymentController");
router.get("/payment", controller_payment.index.bind(controller_payment));
router.get("/payment/:id", controller_payment.show.bind(controller_payment));
const controller_invoice = require("../controllers/admin/invoiceController");
router.get("/invoice", controller_invoice.index.bind(controller_invoice));
router.get("/invoice/:id", controller_invoice.show.bind(controller_invoice));
const controller_subscription = require("../controllers/admin/subscriptionController");
router.get("/subscription", controller_subscription.index.bind(controller_subscription));
router.get("/subscription/:id", controller_subscription.show.bind(controller_subscription));
const controller_wallet = require("../controllers/admin/walletController");
router.get("/wallet", controller_wallet.index.bind(controller_wallet));
router.get("/wallet/:id", controller_wallet.show.bind(controller_wallet));
const controller_notification = require("../controllers/admin/notificationController");
router.get("/notification", controller_notification.index.bind(controller_notification));
router.get("/notification/:id", controller_notification.show.bind(controller_notification));
const controller_message = require("../controllers/admin/messageController");
router.get("/message", controller_message.index.bind(controller_message));
router.get("/message/:id", controller_message.show.bind(controller_message));
const controller_referral = require("../controllers/admin/referralController");
router.get("/referral", controller_referral.index.bind(controller_referral));
router.get("/referral/:id", controller_referral.show.bind(controller_referral));
const controller_reward = require("../controllers/admin/rewardController");
router.get("/reward", controller_reward.index.bind(controller_reward));
router.get("/reward/:id", controller_reward.show.bind(controller_reward));
const controller_analytics = require("../controllers/admin/analyticsController");
router.get("/analytics", controller_analytics.index.bind(controller_analytics));
router.get("/analytics/:id", controller_analytics.show.bind(controller_analytics));
const controller_report = require("../controllers/admin/reportController");
router.get("/report", controller_report.index.bind(controller_report));
router.get("/report/:id", controller_report.show.bind(controller_report));
const controller_audit = require("../controllers/admin/auditController");
router.get("/audit", controller_audit.index.bind(controller_audit));
router.get("/audit/:id", controller_audit.show.bind(controller_audit));
const controller_settings = require("../controllers/admin/settingsController");
router.get("/settings", controller_settings.index.bind(controller_settings));
router.get("/settings/:id", controller_settings.show.bind(controller_settings));
const controller_cms = require("../controllers/admin/cmsController");
router.get("/cms", controller_cms.index.bind(controller_cms));
router.get("/cms/:id", controller_cms.show.bind(controller_cms));
module.exports = router;
