const express = require("express");
const router = express.Router();
const controller_dashboard = require("../controllers/corporate/dashboardController");
router.get("/dashboard", controller_dashboard.index.bind(controller_dashboard));
router.get("/dashboard/:id", controller_dashboard.show.bind(controller_dashboard));
const controller_profile = require("../controllers/corporate/profileController");
router.get("/profile", controller_profile.index.bind(controller_profile));
router.get("/profile/:id", controller_profile.show.bind(controller_profile));
const controller_employee = require("../controllers/corporate/employeeController");
router.get("/employee", controller_employee.index.bind(controller_employee));
router.get("/employee/:id", controller_employee.show.bind(controller_employee));
const controller_department = require("../controllers/corporate/departmentController");
router.get("/department", controller_department.index.bind(controller_department));
router.get("/department/:id", controller_department.show.bind(controller_department));
const controller_training = require("../controllers/corporate/trainingController");
router.get("/training", controller_training.index.bind(controller_training));
router.get("/training/:id", controller_training.show.bind(controller_training));
const controller_course = require("../controllers/corporate/courseController");
router.get("/course", controller_course.index.bind(controller_course));
router.get("/course/:id", controller_course.show.bind(controller_course));
const controller_enrollment = require("../controllers/corporate/enrollmentController");
router.get("/enrollment", controller_enrollment.index.bind(controller_enrollment));
router.get("/enrollment/:id", controller_enrollment.show.bind(controller_enrollment));
const controller_report = require("../controllers/corporate/reportController");
router.get("/report", controller_report.index.bind(controller_report));
router.get("/report/:id", controller_report.show.bind(controller_report));
const controller_invoice = require("../controllers/corporate/invoiceController");
router.get("/invoice", controller_invoice.index.bind(controller_invoice));
router.get("/invoice/:id", controller_invoice.show.bind(controller_invoice));
const controller_notification = require("../controllers/corporate/notificationController");
router.get("/notification", controller_notification.index.bind(controller_notification));
router.get("/notification/:id", controller_notification.show.bind(controller_notification));
module.exports = router;
