const express = require("express");
const router = express.Router();
const controller_dashboard = require("../controllers/expert/dashboardController");
router.get("/dashboard", controller_dashboard.index.bind(controller_dashboard));
router.get("/dashboard/:id", controller_dashboard.show.bind(controller_dashboard));
const controller_profile = require("../controllers/expert/profileController");
router.get("/profile", controller_profile.index.bind(controller_profile));
router.get("/profile/:id", controller_profile.show.bind(controller_profile));
const controller_availability = require("../controllers/expert/availabilityController");
router.get("/availability", controller_availability.index.bind(controller_availability));
router.get("/availability/:id", controller_availability.show.bind(controller_availability));
const controller_specialization = require("../controllers/expert/specializationController");
router.get("/specialization", controller_specialization.index.bind(controller_specialization));
router.get("/specialization/:id", controller_specialization.show.bind(controller_specialization));
const controller_appointment = require("../controllers/expert/appointmentController");
router.get("/appointment", controller_appointment.index.bind(controller_appointment));
router.get("/appointment/:id", controller_appointment.show.bind(controller_appointment));
const controller_consultation = require("../controllers/expert/consultationController");
router.get("/consultation", controller_consultation.index.bind(controller_consultation));
router.get("/consultation/:id", controller_consultation.show.bind(controller_consultation));
const controller_video = require("../controllers/expert/videoController");
router.get("/video", controller_video.index.bind(controller_video));
router.get("/video/:id", controller_video.show.bind(controller_video));
const controller_course = require("../controllers/expert/courseController");
router.get("/course", controller_course.index.bind(controller_course));
router.get("/course/:id", controller_course.show.bind(controller_course));
const controller_student = require("../controllers/expert/studentController");
router.get("/student", controller_student.index.bind(controller_student));
router.get("/student/:id", controller_student.show.bind(controller_student));
const controller_review = require("../controllers/expert/reviewController");
router.get("/review", controller_review.index.bind(controller_review));
router.get("/review/:id", controller_review.show.bind(controller_review));
const controller_earnings = require("../controllers/expert/earningsController");
router.get("/earnings", controller_earnings.index.bind(controller_earnings));
router.get("/earnings/:id", controller_earnings.show.bind(controller_earnings));
const controller_withdrawal = require("../controllers/expert/withdrawalController");
router.get("/withdrawal", controller_withdrawal.index.bind(controller_withdrawal));
router.get("/withdrawal/:id", controller_withdrawal.show.bind(controller_withdrawal));
const controller_notification = require("../controllers/expert/notificationController");
router.get("/notification", controller_notification.index.bind(controller_notification));
router.get("/notification/:id", controller_notification.show.bind(controller_notification));
module.exports = router;
