const express = require("express");
const router = express.Router();
const controller_dashboard = require("../controllers/student/dashboardController");
router.get("/dashboard", controller_dashboard.index.bind(controller_dashboard));
router.get("/dashboard/:id", controller_dashboard.show.bind(controller_dashboard));
const controller_profile = require("../controllers/student/profileController");
router.get("/profile", controller_profile.index.bind(controller_profile));
router.get("/profile/:id", controller_profile.show.bind(controller_profile));
const controller_course = require("../controllers/student/courseController");
router.get("/course", controller_course.index.bind(controller_course));
router.get("/course/:id", controller_course.show.bind(controller_course));
const controller_enrollment = require("../controllers/student/enrollmentController");
router.get("/enrollment", controller_enrollment.index.bind(controller_enrollment));
router.get("/enrollment/:id", controller_enrollment.show.bind(controller_enrollment));
const controller_progress = require("../controllers/student/progressController");
router.get("/progress", controller_progress.index.bind(controller_progress));
router.get("/progress/:id", controller_progress.show.bind(controller_progress));
const controller_assignment = require("../controllers/student/assignmentController");
router.get("/assignment", controller_assignment.index.bind(controller_assignment));
router.get("/assignment/:id", controller_assignment.show.bind(controller_assignment));
const controller_quiz = require("../controllers/student/quizController");
router.get("/quiz", controller_quiz.index.bind(controller_quiz));
router.get("/quiz/:id", controller_quiz.show.bind(controller_quiz));
const controller_certificate = require("../controllers/student/certificateController");
router.get("/certificate", controller_certificate.index.bind(controller_certificate));
router.get("/certificate/:id", controller_certificate.show.bind(controller_certificate));
const controller_appointment = require("../controllers/student/appointmentController");
router.get("/appointment", controller_appointment.index.bind(controller_appointment));
router.get("/appointment/:id", controller_appointment.show.bind(controller_appointment));
const controller_event = require("../controllers/student/eventController");
router.get("/event", controller_event.index.bind(controller_event));
router.get("/event/:id", controller_event.show.bind(controller_event));
const controller_notification = require("../controllers/student/notificationController");
router.get("/notification", controller_notification.index.bind(controller_notification));
router.get("/notification/:id", controller_notification.show.bind(controller_notification));
const controller_message = require("../controllers/student/messageController");
router.get("/message", controller_message.index.bind(controller_message));
router.get("/message/:id", controller_message.show.bind(controller_message));
const controller_wallet = require("../controllers/student/walletController");
router.get("/wallet", controller_wallet.index.bind(controller_wallet));
router.get("/wallet/:id", controller_wallet.show.bind(controller_wallet));
const controller_subscription = require("../controllers/student/subscriptionController");
router.get("/subscription", controller_subscription.index.bind(controller_subscription));
router.get("/subscription/:id", controller_subscription.show.bind(controller_subscription));
const controller_referral = require("../controllers/student/referralController");
router.get("/referral", controller_referral.index.bind(controller_referral));
router.get("/referral/:id", controller_referral.show.bind(controller_referral));
module.exports = router;
